/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author LEWI
 */
public class FormPendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPendaftaran.class.getName());

    private int halamanSekarang = 1;
    private final int limitData = 10;
    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        
        btnPrev.addActionListener(this::btnPrevActionPerformed);
        btnNext.addActionListener(this::btnNextActionPerformed);
        jTableDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDaftarMouseClicked(evt);
            }
        });
        
        tampilkanData();
        loadPasien();
        loadDokter();
        setTanggalHariIni();
    }
    
    public void tampilkanData() {
      DefaultTableModel model = (DefaultTableModel) jTableDaftar.getModel();
    model.setRowCount(0);
 
    String sql = "SELECT no_daftar, id_pasien, id_dokter, tanggal, keluhan FROM pendaftaran";
    
    try {
        Connection conn = config.Koneksi.getKoneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            model.addRow(new Object[]{
                rs.getString("no_daftar"),
                rs.getString("tanggal"),
                rs.getString("id_pasien"), 
                rs.getString("id_dokter"), 
                rs.getString("keluhan")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
    }

    private void loadPasien() {
        cmbPasien.removeAllItems();
        cmbPasien.addItem("- Pilih Pasien -");
        try {
            Connection conn = config.Koneksi.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_pasien FROM pasien");
            while(rs.next()) {
                cmbPasien.addItem(rs.getString("id_pasien"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data pasien: " + e.getMessage());
        }
    }

    private void loadDokter() {
        cmbDokter.removeAllItems();
        cmbDokter.addItem("- Pilih Dokter -");
        try {
            Connection conn = config.Koneksi.getKoneksi();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_dokter FROM dokter");
            while(rs.next()) {
                cmbDokter.addItem(rs.getString("id_dokter"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dokter: " + e.getMessage());
        }
    }

    private void setTanggalHariIni() {
        jCalendar1.setDate(new Date());
    }

    private void bersihForm() {
        txtNoDaftar.setText("");
        setTanggalHariIni();
        cmbPasien.setSelectedIndex(0);
        cmbDokter.setSelectedIndex(0);
        txtKeluhan.setText("");
        txtNoDaftar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDaftar = new javax.swing.JButton();
        txtNoDaftar = new javax.swing.JTextField();
        cmbPasien = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKeluhan = new javax.swing.JTextField();
        cmbDokter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDaftar = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDaftar.setText("Simpan");
        btnDaftar.addActionListener(this::btnDaftarActionPerformed);

        cmbPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("PENDAFTARAN");

        jLabel2.setText("No Pendaftaran");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        jLabel3.setText("Tanggal Pendaftaran");

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        jLabel4.setText("ID Pasien");

        jLabel5.setText("ID Dokter");

        jLabel6.setText("Keluhan");

        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableDaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Daftar", "Tanggal", "ID Pasien", "ID Dokter", "Keluhan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDaftar);

        btnNext.setText("Next>>");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnPrev.setText("<<Prev");
        btnPrev.addActionListener(this::btnPrevActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(btnPrev)
                .addGap(93, 93, 93)
                .addComponent(btnNext)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKeluhan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDokter, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbPasien, 0, 140, Short.MAX_VALUE)
                                    .addComponent(txtNoDaftar)))
                            .addComponent(btnKembali)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBatal)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnDaftar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBatal)
                            .addComponent(btnHapus)
                            .addComponent(btnDaftar))
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrev))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        if (txtNoDaftar.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No Pendaftaran tidak boleh kosong!");
        return;
    }
   
    
    try {
        Connection conn = config.Koneksi.getKoneksi();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String formatTanggal = sdf.format(jCalendar1.getDate());
        
        String sqlCek = "SELECT COUNT(*) FROM pendaftaran WHERE no_daftar = ?";
        PreparedStatement psCek = conn.prepareStatement(sqlCek);
        psCek.setString(1, txtNoDaftar.getText());
        ResultSet rsCek = psCek.executeQuery();
        rsCek.next();
        
        if (rsCek.getInt(1) > 0) {
            String sqlUpdate = "UPDATE pendaftaran SET tgl_daftar=?, id_pasien=?, id_dokter=?, keluhan=? WHERE no_daftar=?";
            PreparedStatement st = conn.prepareStatement(sqlUpdate);
            st.setString(1, cmbPasien.getSelectedItem().toString());
            st.setString(2, cmbDokter.getSelectedItem().toString());
            st.setString(3, formatTanggal);
            st.setString(4, txtKeluhan.getText());
            st.setString(5, txtNoDaftar.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Pendaftaran Berhasil Diperbarui!");
        } else {
            String sqlInsert = "INSERT INTO pendaftaran ( no_daftar, id_pasien, id_dokter, tanggal, keluhan) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement st = conn.prepareStatement(sqlInsert);
            st.setString(1, txtNoDaftar.getText());
            st.setString(2, cmbPasien.getSelectedItem().toString());
            st.setString(3, cmbDokter.getSelectedItem().toString());
            st.setString(4, formatTanggal);
            st.setString(5, txtKeluhan.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Pendaftaran Baru Berhasil Disimpan!");
        }
        
        tampilkanData();
        bersihForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memproses data: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
     bersihForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
      if (txtNoDaftar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Pilih data pendaftaran pada tabel yang ingin dihapus!");
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus transaksi pendaftaran ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if(konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM pendaftaran WHERE no_daftar=?";
                PreparedStatement st = config.Koneksi.getKoneksi().prepareStatement(sql);
                st.setString(1, txtNoDaftar.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Pendaftaran Berhasil Dihapus!");
                tampilkanData();
                bersihForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus: " + e.getMessage());
            }
        } 
    }//GEN-LAST:event_btnHapusActionPerformed
    // TODO add your handling code here:

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
     if (halamanSekarang > 1) {
            halamanSekarang--;
            tampilkanData();
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         if (jTableDaftar.getRowCount() == limitData) {
            halamanSekarang++;
            tampilkanData();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Dashboard1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed
  
    private void jTableDaftarMouseClicked(java.awt.event.MouseEvent evt) {
        int baris = jTableDaftar.rowAtPoint(evt.getPoint());
        if (baris != -1) {
            txtNoDaftar.setText(jTableDaftar.getValueAt(baris, 0).toString());
            try {
                String tglDariTabel = jTableDaftar.getValueAt(baris, 1).toString();
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tglDariTabel);
                jCalendar1.setDate(date);
            } catch (Exception e) {
                setTanggalHariIni();
            }
            
            cmbPasien.setSelectedItem(jTableDaftar.getValueAt(baris, 2).toString());
            cmbDokter.setSelectedItem(jTableDaftar.getValueAt(baris, 3).toString());
            txtKeluhan.setText(jTableDaftar.getValueAt(baris, 4) != null ? jTableDaftar.getValueAt(baris, 4).toString() : "");
        }
    }
    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {
        halamanSekarang = 1;
        tampilkanData();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JComboBox<String> cmbDokter;
    private javax.swing.JComboBox<String> cmbPasien;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDaftar;
    private javax.swing.JTextField txtKeluhan;
    private javax.swing.JTextField txtNoDaftar;
    // End of variables declaration//GEN-END:variables

}